spring:
  application:
    name: Prescription-Service

  datasource:
    url: jdbc:jtds:sqlserver://vNTDACLSCRAPR01:1433/EASY_PRESCRIPTION
    username: easy_prescription_dbo
    password: easy_prescription_dbo123
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
      default_schema: dbo

  